### ISSUE TITLE
Allow Changing the Casing

### ISSUE THREAD

**Issue by krptodr** [pautx24/VsNamespaceFixer#39]
Allow the casing of the namespace to be adjusted. For instance if the folder name is lower case then allow a setting to make the namespace use the folder name, but apply it with proper casing

**Comment by pauer24** [comment]
Hello Chad! I don't quite see the use case here, but feel free to download the code and adapt it yourself!
It should be very easy to implement this change.

Regards and welcome!

P.

**Comment by krptodr** [comment]
Implementing the changes now. I'll push over a pull request. I think you'll be able to see the use case once I do. 

Essentially, it's for old projects that have no structure. Very sloppy. So you might see folder names that have uppercase letters, and some without. But you want your namespaces to follow a consistent pattern. 

This is where the use case comes in for me. 

Therefore, I've implemented it and it's working great. I am adding additional features as well, to help with ASP.NET WebForm projects.

**Comment by pauer24** [comment]
Right... Well I even see it an option in the options section, that might be enabled by default.

**Comment by krptodr** [comment]
@pauer24 I did add an option for it in the options page, along with a set of other options. I just have some code clean up to push up the pull request. 

Do you have a set of requirements when I push up my changes? I think I'll break it up into sections so perhaps two pull requests, one for the topic surrounding this ticket and one for a set of new features. If so, it'll require a local repo clean up. Otherwise, I can just push it all up as on pull request.

Let me know please and thank you.

**Comment by pauer24** [comment]
Hi! You can just pull all in one request :P
