### ISSUE TITLE
"Adjust Namespaces" duplicated in context menu

### ISSUE THREAD

**Issue by akalcik** [pautx24/VsNamespaceFixer#41]
"Adjust Namespaces" is duplicated in the context menu

![image](https://user-images.githubusercontent.com/7405311/117800834-dde90e00-b253-11eb-94ab-b9ca15979db8.png)

Extension Version: 2.9
Visual Studio Version: 16.9.4

**Comment by pauer24** [comment]
Dear Anton, 

I am aware of this issue, yet I can't reproduce it anymore. It may happen sometimes when reinstalling the environment or the extension, but I can't find any solution yet.

Feel free to join us and fix it for you and the rest of users we are using it!

Cheers!

P.
