### ISSUE TITLE
Can Assembly root namespace be taken into consideration?

### ISSUE THREAD

**Issue by Emilian5** [pautx24/VsNamespaceFixer#42]
Hello.

Can the namespace be generated with assembly namespace in mind?

For example:

> Main
>> House
>>> House.asmdef <-- root namespace: House
>>> Couch.cs <-- namespace House {...

**Comment by pautx24** [comment]
As it has no additional vote I don't plan to develop this feature. Feel free to do it yourself if it's required for your needs. It sould be pretty straight forward to do
