### ISSUE TITLE
Namespace duplication when using file scoped namespaces

### ISSUE THREAD

**Issue by lawrence-laz** [pautx24/VsNamespaceFixer#44]
Adjusting namespaces doesn't seem to work with [File Scoped Namespaces](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces):
```csharp
namespace X.Y;
class X
{
}
```
Fixing a namespace in such file results in a duplicate namespace entry:
```csharp
namespace X.Y.Z
{
namespace X.Y;
class X
{
}
}
```

**Comment by pauer24** [comment]
Yes indeed, the solution I figured out was a bit hardcoded...

Would you be so kind to fix it, please? I'm currently out of free time to
fix it.

Regards!!

P.

**Comment by nb-duong** [comment]
I fixed it in [this ](https://github.com/pautx24/VsNamespaceFixer/pull/47)pull request, you can follow it.
