### ISSUE TITLE
Visual Studio 2022 

### ISSUE THREAD

**Issue by nikriaz** [pautx24/VsNamespaceFixer#48]
How to install it on VS2022? You said it's finally compatible but the version from the Marketplace cannot be installed...

![2023-03-24 19_14_57-VSIX Installer](https://user-images.githubusercontent.com/52108512/227607624-2f732875-aef5-4471-9608-c0cf17389977.png)

**Comment by pautx24** [comment]
Just uninstalled it and re-installed it with no issues:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/25298600/230051167-1c4c4ab3-da56-4be9-889d-0d1d7b9a4eaa.png">
The version of my VS2022 is 17.5.3 (64bits) and the language (Options > International settings > Language) is English

**Comment by pautx24** [comment]
Since it cannot be reproduced and no response was given I close the issue
